<?php

namespace App\Http\Controllers;

use App\Models\LogAktivitas;
use App\Models\Pengaturan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Inertia\Inertia;

class PengaturanController extends Controller
{
    public function index()
    {
        $pengaturan = Pengaturan::first();

        return Inertia::render('Pengaturan/Index', [
            'pengaturan' => $pengaturan,
        ]);
    }

    public function update(Request $request)
    {
        $validated = $request->validate([
            'nama_perusahaan' => 'required|string|max:255',
            'alamat' => 'nullable|string|max:255',
            'telepon' => 'nullable|string|max:20',
            'logo' => 'nullable|image|mimes:jpg,jpeg,png|max:2048',
            'sandi_void' => 'nullable|string|max:255',
            'poin_min_belanja' => 'nullable|numeric|min:0',
            'poin_dapat' => 'nullable|integer|min:0',
            'enable_shift' => 'boolean',
            'keyboard_shortcuts' => 'nullable|string',
        ]);

        $pengaturan = Pengaturan::first();

        // Handle keyboard_shortcuts JSON
        if (isset($validated['keyboard_shortcuts'])) {
            $validated['keyboard_shortcuts'] = json_decode($validated['keyboard_shortcuts'], true);
        }

        if ($request->hasFile('logo')) {
            $path = $request->file('logo')->store('logo', 'public');
            $validated['logo'] = $path;
        } else {
            unset($validated['logo']);
        }

        if ($pengaturan) {
            $pengaturan->update($validated);
        } else {
            Pengaturan::create($validated);
        }

        LogAktivitas::create([
            'user_id' => Auth::id(),
            'aktivitas' => 'Mengubah pengaturan aplikasi',
            'tanggal' => now(),
        ]);

        return redirect()->route('pengaturan.index')
            ->with('success', 'Pengaturan berhasil diperbarui.');
    }

    public function backup()
    {
        $user = Auth::user();
        if ($user->level !== 'owner') {
            abort(403, 'Hanya owner yang dapat melakukan backup.');
        }

        $tables = DB::select('SHOW TABLES');
        $dbName = DB::getDatabaseName();
        $key = 'Tables_in_' . $dbName;

        $sql = "-- Backup Database: {$dbName}\n";
        $sql .= "-- Tanggal: " . now()->format('Y-m-d H:i:s') . "\n";
        $sql .= "-- Generated by PAPAN\n\n";
        $sql .= "SET FOREIGN_KEY_CHECKS=0;\n\n";

        foreach ($tables as $table) {
            $tableName = $table->$key;

            // Get CREATE TABLE statement
            $createTable = DB::select("SHOW CREATE TABLE `{$tableName}`");
            $sql .= "-- Struktur tabel: {$tableName}\n";
            $sql .= "DROP TABLE IF EXISTS `{$tableName}`;\n";
            $sql .= $createTable[0]->{'Create Table'} . ";\n\n";

            // Get all rows
            $rows = DB::table($tableName)->get();
            if ($rows->count() > 0) {
                $sql .= "-- Data tabel: {$tableName}\n";
                foreach ($rows as $row) {
                    $values = collect((array) $row)->map(function ($value) {
                        if (is_null($value)) {
                            return 'NULL';
                        }
                        return "'" . addslashes($value) . "'";
                    })->implode(', ');

                    $columns = collect(array_keys((array) $row))->map(fn($col) => "`{$col}`")->implode(', ');
                    $sql .= "INSERT INTO `{$tableName}` ({$columns}) VALUES ({$values});\n";
                }
                $sql .= "\n";
            }
        }

        $sql .= "SET FOREIGN_KEY_CHECKS=1;\n";

        LogAktivitas::create([
            'user_id' => Auth::id(),
            'aktivitas' => 'Melakukan backup database',
            'tanggal' => now(),
        ]);

        $filename = 'backup_' . $dbName . '_' . now()->format('Ymd_His') . '.sql';

        return response($sql)
            ->header('Content-Type', 'application/sql')
            ->header('Content-Disposition', "attachment; filename=\"{$filename}\"");
    }

    public function restore(Request $request)
    {
        $user = Auth::user();
        if ($user->level !== 'owner') {
            abort(403, 'Hanya owner yang dapat melakukan restore.');
        }

        $request->validate([
            'sql_file' => 'required|file|mimes:sql',
        ]);

        $content = file_get_contents($request->file('sql_file')->getRealPath());

        DB::statement('SET FOREIGN_KEY_CHECKS=0');

        $statements = array_filter(
            array_map('trim', explode(';', $content)),
            fn($stmt) => !empty($stmt) && !str_starts_with($stmt, '--')
        );

        foreach ($statements as $statement) {
            // Skip comments and empty lines
            $clean = trim($statement);
            if (empty($clean) || str_starts_with($clean, '--')) {
                continue;
            }
            try {
                DB::unprepared($clean . ';');
            } catch (\Exception $e) {
                // Continue on error to process remaining statements
                continue;
            }
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        LogAktivitas::create([
            'user_id' => Auth::id(),
            'aktivitas' => 'Melakukan restore database',
            'tanggal' => now(),
        ]);

        return redirect()->route('pengaturan.index')
            ->with('success', 'Database berhasil di-restore.');
    }
}
